### PR TITLE
Updated configs to support running in QEMU

### PR DESCRIPTION
**Pull request by vaibhavkulkarni**
I confess I am not totally sure on the place to change. But, I was able to run both KML and Non-KML kernels using the config changes in the PR using the below the command on Linux host as an example:

`qemu-system-x86_64 -enable-kvm -no-reboot 
    -kernel kernelbuild/lupine-djw-nokml++nginx/vmlinuz  
    -drive "file=./nginx.ext2,format=raw,if=none,id=hd0" -nographic -nodefaults -serial stdio 
    -netdev user,id=mynet0,net=192.168.76.0/24 
    -device virtio-blk-pci,id=blk0,drive=hd0,scsi=off 
    -append "panic=-1 console=ttyS0 root=/dev/vda rw loglevel=15 nokaslr init=/guest_start.sh /usr/sbin/nginx"`

### CODE REVIEW

**Comment by hckuo** [comment]
I meant can you update the readme and add a section for the changes you have made?

**Comment by vaibhavkulkarni** [comment]
Sure. I can. But one of my changes for nokml, also fixes an issue with kernel build.

**Comment by a74731248** [comment]
> Sure. I can. But one of my changes for nokml, also fixes an issue with kernel build. Kernel doesn't compile if `CONFIG_PARAVIRT` is set.
> 
> Also, do you mean the changes are not required and you just need README.md update?

Is that speed up the boot of Lupine while using the kml and `CONFIG_PARAVIRT`?

**Comment by vaibhavkulkarni** [comment]
> I meant can you update the readme and add a section for the changes you have made?

You mind replying to my comment [above](https://github.com/hckuo/Lupine-Linux/pull/49#issuecomment-926743979) please?

**Comment by vaibhavkulkarni** [comment]
> > Sure. I can. But one of my changes for nokml, also fixes an issue with kernel build. Kernel doesn't compile if `CONFIG_PARAVIRT` is set.
> > Also, do you mean the changes are not required and you just need README.md update?
> 
> Is that speed up the boot of Lupine while using the kml and `CONFIG_PARAVIRT`?

KML config doesn't have `CONFIG_PARAVIRT` enabled.

**Comment by hckuo** [comment]
> Also, do you mean the changes are not required and you just need README.md update?

Yes!

**Comment by vaibhavkulkarni** [comment]
Closing it as per above. I will update README.md and raise another PR. I will also file an issue on the nokml build issue.

**Pull request closed without merging**
